version: '3.9'

services:  
  biobank_db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biobank_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - "./biobank-db.sql:/docker-entrypoint-initdb.d/1.sql"
    container_name: biobank_db
